### ISSUE TITLE
isDiffBetweenDates checks that different between timestamps is exactly the difference, rather than less than

### ISSUE THREAD

**Issue by pwn493** [JBZoo/PHPUnit#16]
https://github.com/JBZoo/PHPUnit/blob/master/src/functions/aliases.php#L503

Either the comment should be changed to say "Diff between dates: {$date1} and {$date2} is not exactly {$timeDiff} seconds. {$message}", or the === operator should be changed to <

**Comment by SmetDenis** [comment]
Thank you @pwn493 
I fixed it in version 4.11.0
